version: "3.7"

services:

  db:
    container_name: MySQL
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=weather
    networks:
      - test-network

  back:
    container_name: Laravel
    depends_on:
      - db
    image: laravel
    build: ./api
    working_dir: /var/www/
    volumes:
      - ./api:/var/www/
      - ./api/public/:/var/www/html/
    ports: 
      - "8080:8080"
      - "8000:8000"  
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=weather
      - DB_USERNAME=root
      - DB_PASSWORD=
    command: bash -c "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host 0.0.0.0"
    networks:
      - test-network
  
  front:
    container_name: Reactjs
    depends_on:
      - back    
    restart: unless-stopped
    image: node:18
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend/build:/app    
    networks:
      - test-network
    command: "npx serve"

networks:
  test-network:
    driver: bridge